
import DatabaseManager.databaseManager;
import beanClass.customerBean;
import java.awt.event.ActionEvent;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ammar
 */
public class Customer extends javax.swing.JFrame {
    public Customer() {
       initComponents();
          try {
            getCustomer();
            customerIdList.addListSelectionListener((ListSelectionListener) this);
        } catch (Exception ex) {
           
        }
    }
    private void getCustomer(){
    try{
        Vector v=databaseManager.getCustomer();
        customerIdList.setListData(v);
    }catch(Exception e){
        e.printStackTrace ();
      JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
    }
    }//end Customer  
      public void actionPerformed(ActionEvent e){
        if(e.getSource()==addButton)
            addRecord();
        if(e.getSource()==backButton){
         hide();
         } 
        if(e.getSource()==clearButton)
            clear();
    }
    private void clear(){
       // customerIdTextField.setText("");
        firstNameTextField.setText("");
        lastNameTextField.setText("");
        cityTextField.setText("");
        stateTextField.setText("");
        countryTextField.setText("");
        addressTextField.setText("");
        emailTextField.setText("");
        dateOfCreateTextField.setText("");
        contactNoTextField.setText("");
        remarksTextPane.setText("");
        
    }// end clear
 private void addRecord(){
            String  firstName    =firstNameTextField.getText();
            String  lastName     =lastNameTextField.getText();
            String  city         =cityTextField.getText();
            String  state        =stateTextField.getText();
            String  country      =countryTextField.getText();
            String  address      =addressTextField.getText();
            String  email        = emailTextField.getText();
            String  dateOfCreate =dateOfCreateTextField.getText();
            String  contactNo    =contactNoTextField.getText();
            String  remarks      =remarksTextPane.getText();
            try{
                int rows=databaseManager.addCustomer(firstName,lastName,city,state,country,address,email,dateOfCreate,contactNo,remarks);
                if(rows>=1)
                    JOptionPane.showMessageDialog(this, rows+"RECORD INSERTED ");
                clear();
                getCustomer();
            }catch(Exception e){
                   JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
                   e.printStackTrace();
            }
    }//end addRecord
    private void updateRecord(){
         customerBean bean=(customerBean)customerIdList.getSelectedValue();
         if(bean==null)return ;
         try{
          int rows=databaseManager.updateCustomer(bean.getCustomerId(),firstNameTextField.getText(),lastNameTextField.getText(),cityTextField.getText(),stateTextField.getText(),countryTextField.getText(),addressTextField.getText(),emailTextField.getText(),dateOfCreateTextField.getText(),contactNoTextField.getText(),remarksTextPane.getText());
            
                if(rows>=1)
                    JOptionPane.showMessageDialog(this, rows+"RECORD UPDATED ");
                clear();
                getCustomer();
            }catch(Exception e){
                   JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
                   e.printStackTrace();
            }
         }//end updateRecord
    private void deleteRecord(){
    customerBean bean = (customerBean)customerIdList.getSelectedValue();
    if(bean==null)return;
    try{
        int rows = databaseManager.deleteCustomer(bean.getCustomerId());
          if(rows>=1)
                    JOptionPane.showMessageDialog(this, rows+" RECORD DELETED ");
                clear();
                getCustomer();
            }catch(Exception e){
                   JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
                   e.printStackTrace();
            }
         } //end deleteRecord
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        dateOfCreateLabel = new javax.swing.JLabel();
        contactNoLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        remarksLabel = new javax.swing.JLabel();
        customerIdTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        stateTextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        contactNoTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        dateOfCreateTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerIdList = new javax.swing.JList();
        customerIdLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        remarksTextPane = new javax.swing.JTextPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 255));
        setMaximumSize(new java.awt.Dimension(750, 750));
        setMinimumSize(new java.awt.Dimension(850, 850));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("CUSTOMER ID LIST");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 60, 140, 20);

        lastNameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lastNameLabel.setText("LAST NAME");
        getContentPane().add(lastNameLabel);
        lastNameLabel.setBounds(80, 160, 90, 40);

        cityLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cityLabel.setText("CITY");
        getContentPane().add(cityLabel);
        cityLabel.setBounds(120, 210, 50, 40);

        stateLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        stateLabel.setText("STATE");
        getContentPane().add(stateLabel);
        stateLabel.setBounds(120, 260, 50, 40);

        countryLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        countryLabel.setText("COUNTRY");
        getContentPane().add(countryLabel);
        countryLabel.setBounds(90, 310, 80, 40);

        addressLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addressLabel.setText("ADDRESS");
        getContentPane().add(addressLabel);
        addressLabel.setBounds(90, 360, 80, 40);

        emailLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailLabel.setText("EMAIL");
        getContentPane().add(emailLabel);
        emailLabel.setBounds(120, 410, 50, 40);

        dateOfCreateLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dateOfCreateLabel.setText("DATE OF CREATE");
        getContentPane().add(dateOfCreateLabel);
        dateOfCreateLabel.setBounds(40, 460, 130, 40);

        contactNoLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contactNoLabel.setText("CONTACT NO");
        getContentPane().add(contactNoLabel);
        contactNoLabel.setBounds(70, 500, 100, 40);

        addressTextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(addressTextField);
        addressTextField.setBounds(170, 360, 320, 40);

        remarksLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        remarksLabel.setText("REMARKS");
        getContentPane().add(remarksLabel);
        remarksLabel.setBounds(90, 560, 70, 17);

        customerIdTextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        customerIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(customerIdTextField);
        customerIdTextField.setBounds(170, 60, 130, 40);

        firstNameTextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(firstNameTextField);
        firstNameTextField.setBounds(170, 110, 320, 40);

        lastNameTextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(lastNameTextField);
        lastNameTextField.setBounds(170, 160, 320, 40);

        cityTextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(cityTextField);
        cityTextField.setBounds(170, 210, 320, 40);

        stateTextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(stateTextField);
        stateTextField.setBounds(170, 260, 320, 40);

        countryTextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(countryTextField);
        countryTextField.setBounds(170, 310, 320, 40);

        jTextField8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(jTextField8);
        jTextField8.setBounds(170, 360, 320, 40);

        contactNoTextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contactNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(contactNoTextField);
        contactNoTextField.setBounds(170, 510, 320, 40);

        emailTextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(emailTextField);
        emailTextField.setBounds(170, 410, 320, 40);

        dateOfCreateTextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(dateOfCreateTextField);
        dateOfCreateTextField.setBounds(170, 460, 130, 40);

        customerIdList.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        customerIdList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                customerIdListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(customerIdList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(500, 80, 160, 570);

        customerIdLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        customerIdLabel.setText("CUSTOMER ID");
        getContentPane().add(customerIdLabel);
        customerIdLabel.setBounds(60, 60, 110, 40);

        firstNameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        firstNameLabel.setText("FIRST NAME");
        getContentPane().add(firstNameLabel);
        firstNameLabel.setBounds(70, 110, 100, 40);

        deleteButton.setBackground(new java.awt.Color(255, 0, 204));
        deleteButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton);
        deleteButton.setBounds(410, 670, 75, 50);

        addButton.setBackground(new java.awt.Color(255, 0, 204));
        addButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(170, 670, 60, 50);

        updateButton.setBackground(new java.awt.Color(255, 0, 204));
        updateButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton);
        updateButton.setBounds(240, 670, 79, 50);

        clearButton.setBackground(new java.awt.Color(255, 0, 204));
        clearButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton);
        clearButton.setBounds(330, 670, 70, 50);

        backButton.setBackground(new java.awt.Color(255, 0, 0));
        backButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(500, 670, 160, 50);

        remarksTextPane.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jScrollPane2.setViewportView(remarksTextPane);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(170, 560, 320, 90);
        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(740, 30, 0, 0);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel3.setBackground(new java.awt.Color(0, 204, 255));
        jLabel3.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        jLabel3.setText("CUSTOMER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(100, 0, 560, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerIdListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_customerIdListValueChanged
       customerBean bean=(customerBean)customerIdList.getSelectedValue();
       if(bean==null)return;
       
       customerIdTextField.setText(""+bean.getCustomerId());
       firstNameTextField.setText(bean.getFirstName());
       lastNameTextField.setText(""+bean.getLastName());
       cityTextField.setText(bean.getCity());
       stateTextField.setText(""+bean.getState());
       countryTextField.setText(bean.getCountry());
       addressTextField.setText(""+bean.getAddress());
       emailTextField.setText(bean.getEmail());
       dateOfCreateTextField.setText(""+bean.getDateOfCreate());
       contactNoTextField.setText(""+bean.getContactNo());
       remarksTextPane.setText(bean.getRemarks());
    }//GEN-LAST:event_customerIdListValueChanged

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        addRecord();
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        updateRecord();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        deleteRecord();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void customerIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIdTextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
         hide();
    }//GEN-LAST:event_backButtonActionPerformed

    private void contactNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel contactNoLabel;
    private javax.swing.JTextField contactNoTextField;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JLabel customerIdLabel;
    private javax.swing.JList customerIdList;
    private javax.swing.JTextField customerIdTextField;
    private javax.swing.JLabel dateOfCreateLabel;
    private javax.swing.JTextField dateOfCreateTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel remarksLabel;
    private javax.swing.JTextPane remarksTextPane;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
