
import DatabaseManager.databaseManager;
import beanClass.transactionBean;
import javax.swing.JOptionPane;

import beanClass.accountBean;
import beanClass.customerBean;

import java.util.Vector;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ammar
 */
public class Withdraw extends javax.swing.JFrame {

    /**
     * Creates new form Withdraw
     */
    public Withdraw() {
        initComponents();
        getCustomer();
    }
    public void clear(){
        amountTF.setText("");
        dateOfTransactionTF.setText("");
        amountTypeTF.setText("");
        chequeTF.setText("");
    }
    private void getCustomer(){
      
    try{
        Vector v=databaseManager.getCustomer();
       customerC.removeAllItems();
           for(int i=0; i<v.size();  i++ ){ 
        customerBean  bean =(customerBean)v.elementAt(i);
        customerC.addItem(bean);
    } 

    }catch(Exception e){
        e.printStackTrace ();
      JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
    
    }      
    }
    
      private void getAccount(){
            customerBean bean=(customerBean) customerC.getSelectedItem();
            if(bean==null) return;
            try{
                accountC.removeAllItems();
                 Vector v=databaseManager.getAccount(bean.getCustomerId());

            for(int i=0;i<v.size();i++){
                accountBean bean1=(accountBean)v.elementAt(i);
                accountC.addItem(bean1);

            }
        }//end try block
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Error : "+e.getMessage());
        }//end catch
        }
  
private void getTransaction(){
            accountBean bean = (accountBean)accountC.getSelectedItem();
           if(bean==null)return;
           try{
               Vector v = databaseManager.getTransaction(bean.getAccountId());
              // TransactionL.setListData(v);
           }catch(Exception e){
              e.printStackTrace();
              JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
           }
           
       }
     private void addRecord(){
    transactionBean bean = new      transactionBean();
    accountBean bean1 = (accountBean)accountC.getSelectedItem();
    int tra = bean.getTransId();

    int accountNo = bean1.getAccountId();
    int cheque = Integer.parseInt(chequeTF.getText());
    String transactionType = "TRANSFER ";
    int  amount = Integer.parseInt(amountTF.getText());    
    String dateOfTransaction = dateOfTransactionTF.getText();
    String amountType = amountTypeTF.getText();
    
    try{
        int row = databaseManager.addTransactionW(tra,accountNo, amount,  amountType, dateOfTransaction,transactionType,cheque);
        if(row>=1)
                JOptionPane.showMessageDialog(this," WITHDRAW DONE ");
                //clear();
            //    getTransaction();
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,"erorr"+e.getMessage());
        e.printStackTrace();}
    
    
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dateOfTransactionTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        amountTypeTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        chequeTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        accountC = new javax.swing.JComboBox();
        customerC = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 650));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        amountTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(amountTF);
        amountTF.setBounds(170, 240, 340, 50);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("DATE OF TRANASACTION");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 300, 150, 50);

        jButton1.setBackground(new java.awt.Color(204, 0, 204));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("WITHDRAW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 480, 210, 50);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BACK");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 480, 120, 50);

        dateOfTransactionTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(dateOfTransactionTF);
        dateOfTransactionTF.setBounds(170, 300, 340, 50);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText(" AMOUNT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 240, 60, 50);

        amountTypeTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(amountTypeTF);
        amountTypeTF.setBounds(170, 360, 340, 50);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("AMOUNT TYPE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 360, 90, 50);
        getContentPane().add(chequeTF);
        chequeTF.setBounds(170, 420, 340, 50);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("CHEQUE NO");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(100, 420, 70, 50);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("ACCOUNT ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 140, 60, 50);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("CUSTOMER");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 80, 70, 50);

        accountC.setEditable(true);
        accountC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(accountC);
        accountC.setBounds(170, 140, 340, 50);

        customerC.setEditable(true);
        customerC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        customerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerCActionPerformed(evt);
            }
        });
        getContentPane().add(customerC);
        customerC.setBounds(170, 80, 340, 50);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        jLabel1.setText("WITHDRAW");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 10, 540, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        addRecord();
        clear();
        TransactionTypes ob= new TransactionTypes();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        TransactionTypes ob= new TransactionTypes();
        ob.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton2MouseClicked

    private void customerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerCActionPerformed
        getAccount();
    }//GEN-LAST:event_customerCActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Withdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accountC;
    private javax.swing.JTextField amountTF;
    private javax.swing.JTextField amountTypeTF;
    private javax.swing.JTextField chequeTF;
    private javax.swing.JComboBox customerC;
    private javax.swing.JTextField dateOfTransactionTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
